app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  git-base-url: https://api.github.com/repos/
  sof-base-url: https://api.stackexchange.com/2.3/questions/
  max-attempts: 3

spring:
  application:
    name: scrapper
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
